name: Docker Image stable

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
      matrix:
        config:
          - { base: latest, user: "root", java: 8 }
          - { base: dind, user: "root", java: 8 }
          - { base: dind-rootless, user: "rootless", java: 8 }
          - { base: latest-java11, user: "root", java: 11 }
          - { base: dind-java11, user: "root", java: 11 }
          - { base: dind-rootless-java11, user: "rootless", java: 11 }
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          add_git_labels: true
          repository: ${{ github.repository }}
          tags: ${{ matrix.config.base }}
          build_args: IMAGE_BASE=${{ matrix.config.base }},IMAGE_USER=${{ matrix.config.user }},JAVA=${{ matrix.config.java }}