name: Docker Image stable PR

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    strategy:    
      fail-fast: false
      matrix:
        config:
          - { base: latest, user: "root", java: 8 }
          - { base: dind, user: "root", java: 8 }
          - { base: dind-rootless, user: "rootless", java: 8 }
          - { base: latest, user: "root", java: 11, imageSuffix: "-java11" }
          - { base: dind, user: "root", java: 11, imageSuffix: "-java11" }
          - { base: dind-rootless, user: "rootless", java: 11, imageSuffix: "-java11" }
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          add_git_labels: true
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ github.event.repository.name }}
          tags: ${{ matrix.config.base }}${{ matrix.config.imageSuffix }}-PR-${{github.event.number}}
          build_args: IMAGE_BASE=${{ matrix.config.base }},IMAGE_USER=${{ matrix.config.user }},JAVA_VERSION_ARG:${{ matrix.config.java }}